modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/MC-U-Team/U-Team-Core/issues"
displayURL="https://u-team.info/mods/uteamcore"
logoFile="logo.png"
license="Apache-2.0 License"
credits="Team U-Team"
authors="HyCraftHD, MrTroble"

[[mods]]
	modId="uteamcore"
	version="${file.jarVersion}"
	displayName="U Team Core"
	updateJSONURL="https://api.u-team.info/update/uteamcore.json"
	description="This library contains many useful modding stuff!"
	
	[[dependencies.uteamcore]]
	    modId="forge"
	    mandatory=true
	    versionRange="[35.1.10,)"
	    ordering="NONE"
	    side="BOTH"
	
	[[dependencies.uteamcore]]
	    modId="minecraft"
	    mandatory=true
	    versionRange="[1.16.4]"
	    ordering="NONE"
	    side="BOTH"